#!/bin/bash

PATH_TO_DESKTOP="/usr/share/applications/cmaptools.desktop"
PATH_TO_INSTALL_DIR=""

create_desktop(){
	:> $PATH_TO_DESKTOP
	echo "[Desktop Entry]" >> $PATH_TO_DESKTOP
	echo "Encoding=UTF-8" >> $PATH_TO_DESKTOP
	echo "Name=CmapTools" >> $PATH_TO_DESKTOP
	echo "Comment=Tool to create concept maps" >> $PATH_TO_DESKTOP
	echo "Comment[ca_ES.utf8@valencia]=Eina per a crear mapes conceptuals" >> $PATH_TO_DESKTOP
	echo "Comment[es]=Herramienta para crear mapas conceptuales" >> $PATH_TO_DESKTOP
	echo "Comment[ca@valencia]=Eina per a crear mapes conceptuals" >> $PATH_TO_DESKTOP
	echo "Icon=cmaptools.png" >> $PATH_TO_DESKTOP
	echo "Exec="$1"/CmapTools">> $PATH_TO_DESKTOP
	echo "Terminal=false" >> $PATH_TO_DESKTOP
	echo "Type=Application" >> $PATH_TO_DESKTOP
	echo "Categories=Application;Education" >> $PATH_TO_DESKTOP
	echo "StartupNotify=false" >> $PATH_TO_DESKTOP
	echo "TryExec="$1"/CmapTools" >> $PATH_TO_DESKTOP
}

ACTION="$1"

case $ACTION in

	preInstall)

		if [ ! -d /usr/share/llx-cmaptools/out ]; then
			mkdir -p /usr/share/llx-cmaptools/out
		fi

	;;

	postInstall)
		
		/usr/share/llx-cmaptools/Linux64CmapTools_v6.04_09-24-19.bin -f /usr/share/llx-cmaptools/cmaptools.template -r /usr/share/llx-cmaptools/out/result.txt
		
	
		if [ "$?" -eq 1 ];then
			PATH_TO_INSTALL_DIR=$(cat /usr/share/llx-cmaptools/out/result.txt | grep USER_INSTALL_DIR | cut -d"=" -f2)

			if [ ! -d $PATH_TO_INSTALL_DIR ]; then	
				exit 1
			fi
			create_desktop $PATH_TO_INSTALL_DIR
		else
			exit 1
		fi		
		
	;;

	remove)
	
		echo "Launching uninstaller..."

		DIRECTORY_CMAPTOOLS="/usr/share/IHMC_CmapTools"
		if [ -d $DIRECTORY_CMAPTOLS ];then
			"/usr/share/IHMC_CmapTools/Uninstall CmapTools"

			if [ "$?" -eq 0 ];then
				apt-get remove -y lliurex-cmaptools
				TEST=$( dpkg-query -s  lliurex-cmaptools 2> /dev/null| grep Status | cut -d " " -f 4 )
				if [ "$TEST" == 'installed' ];then
					exit 1
				fi

				DESKTOP_PATH="/usr/share/applications/cmaptools.desktop"
				if [ -f $DESKTOP_PATH ];then
					rm -f $DESKTOP_PATH

				fi
			else
				exit 1
			fi	
		else
			exit 1
		fi		
	;;	

esac

exit 0	

		